-- Rulează o singură dată în Supabase SQL Editor.
create table if not exists public.course_subscribers (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  source text not null default 'registration',
  gdpr_accepted boolean not null check (gdpr_accepted = true),
  gdpr_accepted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists course_subscribers_created_at_idx
  on public.course_subscribers (created_at desc);

alter table public.course_subscribers add column if not exists source text not null default 'registration';
revoke insert on public.course_subscribers from anon, authenticated;
alter table public.course_subscribers enable row level security;

drop policy if exists "Public can register for courses" on public.course_subscribers;
-- Submissions use the API service role after distributed rate limiting.
