-- Rulează o singură dată în Supabase SQL Editor.
create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  image text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.product_categories(id) on delete cascade,
  title text not null,
  description text not null default '',
  price text not null,
  dimensions text not null,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint products_images_array check (
    jsonb_typeof(images) = 'array'
    and jsonb_array_length(images) between 1 and 2
  )
);

create index if not exists products_category_idx
  on public.products (category_id, created_at);

drop trigger if exists set_product_categories_updated_at on public.product_categories;
create trigger set_product_categories_updated_at
before update on public.product_categories
for each row execute function public.set_updated_at();

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

grant select on public.product_categories to anon, authenticated;
grant select on public.products to anon, authenticated;

alter table public.product_categories enable row level security;
alter table public.products enable row level security;

drop policy if exists "Public can read product categories" on public.product_categories;
create policy "Public can read product categories"
on public.product_categories for select using (true);

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select using (true);
