create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  key text not null unique,
  content jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null default '',
  email text not null,
  phone text not null,
  project_details text not null,
  status text not null default 'Nou',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'footer',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.galleries (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  gallery_id bigint not null references public.galleries(id) on delete cascade,
  url text not null,
  filename text not null,
  original_name text not null,
  size integer not null,
  mime_type text not null,
  width integer,
  height integer,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists gallery_items_gallery_sort_idx
  on public.gallery_items (gallery_id, sort_order, created_at);

create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);

create index if not exists newsletter_subscribers_created_at_idx
  on public.newsletter_subscribers (created_at desc);

drop trigger if exists set_site_content_updated_at on public.site_content;
create trigger set_site_content_updated_at
before update on public.site_content
for each row
execute function public.set_updated_at();

drop trigger if exists set_galleries_updated_at on public.galleries;
create trigger set_galleries_updated_at
before update on public.galleries
for each row
execute function public.set_updated_at();

grant usage on schema public to anon, authenticated;
grant select on public.site_content to anon, authenticated;
grant select on public.galleries to anon, authenticated;
grant select on public.gallery_items to anon, authenticated;
grant insert on public.newsletter_subscribers to anon, authenticated;
grant insert on public.inquiries to anon, authenticated;

alter table public.site_content enable row level security;
alter table public.inquiries enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.galleries enable row level security;
alter table public.gallery_items enable row level security;

drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
on public.site_content
for select
using (true);

drop policy if exists "Public can read galleries" on public.galleries;
create policy "Public can read galleries"
on public.galleries
for select
using (true);

drop policy if exists "Public can read gallery items" on public.gallery_items;
create policy "Public can read gallery items"
on public.gallery_items
for select
using (true);

drop policy if exists "Public can submit inquiries" on public.inquiries;
create policy "Public can submit inquiries"
on public.inquiries
for insert
with check (true);

drop policy if exists "Public can subscribe to newsletter" on public.newsletter_subscribers;
create policy "Public can subscribe to newsletter"
on public.newsletter_subscribers
for insert
with check (true);
